// SPDX-License-Identifier: AGPL-3.0-only
/** Error codes that any endpoint may return. Domain codes live in `<domain>/errors.ts`. */
export const COMMON_ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  AUTH_UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  ACCESS_FORBIDDEN: 'ACCESS_FORBIDDEN',
  ACCESS_EXCEEDS_PARENT: 'ACCESS_EXCEEDS_PARENT',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',
  LIMIT_REACHED: 'LIMIT_REACHED',
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',
  CREDITS_EXHAUSTED: 'CREDITS_EXHAUSTED', // Cloud platform models; HTTP 402
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const

/** Codes produced by the web clients themselves (never by the API). */
export const CLIENT_ERROR_CODES = {
  NETWORK_ERROR: 'NETWORK_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const
