// SPDX-License-Identifier: AGPL-3.0-only
import { libraryConfig } from '@surefy/config/eslint'

export default [
  ...libraryConfig({ tsconfigRootDir: import.meta.dirname }),
  {
    // Primitives are generated by the shadcn CLI and kept close to upstream so `shadcn diff` stays
    // useful; these style rules would rewrite most of each file without changing behavior.
    files: ['src/primitives/**'],
    rules: {
      '@typescript-eslint/naming-convention': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      'sonarjs/prefer-read-only-props': 'off',
      'sonarjs/no-redundant-optional': 'off',
    },
  },
]
